CREATE TABLE IF NOT EXISTS categories
(
id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
name  VARCHAR(50)                                         NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
email  VARCHAR(254)                                        NOT NULL,
id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
name   VARCHAR(250)                                        NOT NULL,
banned TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS locations (
id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
lat NUMERIC                                             NOT NULL,
lon NUMERIC                                             NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
annotation         VARCHAR(2000)                                       NOT NULL,
category_id        BIGINT                                              NOT NULL,
confirmed_requests BIGINT                                              NOT NULL,
created            TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
description        VARCHAR(7000)                                       NOT NULL,
event_date         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
initiator_id       BIGINT                                              NOT NULL,
location_id        BIGINT                                              NOT NULL,
paid               BOOLEAN                                             NOT NULL,
participant_limit  BIGINT                                              NOT NULL,
published          TIMESTAMP WITHOUT TIME ZONE,
moderation         BOOLEAN                                             NOT NULL,
state              VARCHAR(15)                                         NOT NULL,
title              VARCHAR(120)                                        NOT NULL,
views              BIGINT,
FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE,
FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
text       VARCHAR(2000)                                       NOT NULL,
date       TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
author_id  BIGINT                                              NOT NULL,
event_id   BIGINT                                              NOT NULL,
FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations
(
id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
pinned BOOLEAN                                             NOT NULL,
title  VARCHAR(50)                                         NOT NULL
);

CREATE TABLE IF NOT EXISTS join_compilations_events
(
comp_id   BIGINT REFERENCES compilations (id) ON DELETE CASCADE NOT NULl,
event_id  BIGINT REFERENCES events (id)       ON DELETE CASCADE NOT NULl,
CONSTRAINT join_compilations_events_pk PRIMARY KEY (comp_id, event_id)
);

CREATE TABLE IF NOT EXISTS requests
(
created      TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
event_id     BIGINT                                              NOT NULL,
id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
requester_id BIGINT                                              NOT NULL,
status       VARCHAR(20)                                         NOT NULL,
FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);
